blog/urls.py
from django.urls import path
from .views import BlogView, BlogDetailView, BlogFactDetailView



# blog/urls.py
app_name = 'blog'
urlpatterns = [
     path('', BlogView.as_view(), name='blogurl'),
     path('blog/<slug:slug>/', BlogDetailView.as_view(), name='blogdetailurl'),
     path('blog/fact/<slug:slug>/', BlogFactDetailView.as_view(), name='blogfactdetailurl'),
]

coffee/urls.py
from django.urls import path
from .views import HomeView

urlpatterns = [
     path('', HomeView, name='coffeeindex')
]

conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('richtextfield/', include('djrichtextfield.urls')), 
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('blog.urls')),
    path('', include('coffee.urls')),
]




if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models

# Create your models here.



class BaseModel(models.Model):
     """
     Base model that provides created_at and updated_at fields.
     """
     created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created At")
     updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated At")
     is_active = models.BooleanField(default=True, verbose_name="Is Active")
     is_featured = models.BooleanField(default=False, verbose_name="Is Featured")
     is_selling = models.BooleanField(default=False, verbose_name="Is Selling")
     is_fact = models.BooleanField(default=False, verbose_name="Is Fact")
     is_popular = models.BooleanField(default=False, verbose_name="Is Popular")
     is_deleted = models.BooleanField(default=False, verbose_name="Is Deleted")
     is_trending = models.BooleanField(default=False, verbose_name="Is Trending")



     class Meta:
          abstract = True  # This model will not create a table in the database
          ordering = ['-created_at']  # Default ordering by created_at descending

blog/models.py
from django.db import models
from django.utils.text import slugify
from base.models import BaseModel




class Status(BaseModel):
     icon = models.ImageField(upload_to='status_icon/' ,blank=True, null=True)
     name = models.CharField(max_length=100, unique=True)


     def __str__(self):
          return f'{self.icon.url} - {self.name}'



class Blog(BaseModel):
     title = models.CharField(max_length=200)
     slug = models.SlugField(unique=True, blank=True)
     subtitle = models.CharField(max_length=200, blank=True, null=True)
     content = models.TextField()
     image = models.ImageField(upload_to='blog_images/', blank=True, null=True)
     author = models.CharField(max_length=100, blank=True, null=True)
     status = models.ForeignKey(Status, on_delete=models.CASCADE, related_name='blog_status', blank=True, null=True)
     views = models.PositiveIntegerField(default=0)
     likes = models.PositiveIntegerField(default=0)
     

     def save(self, *args, **kwargs):
          if not self.slug:
               self.slug = slugify(self.title,  allow_unicode=True)
          return super().save(*args, **kwargs)


     def __str__(self):
          return f'{self.title} - {self.author if self.author else "Unknown Author"}'

coffee/models.py
from django.db import models
from django.utils.text import slugify
# from djrichtextfield.models import RichTextField
from ckeditor.fields import RichTextField # Agar rasm yuklash kerak bo'lmasa
from ckeditor_uploader.fields import RichTextUploadingField # <--- Rasm yuklash funksiyasi uchun buni ishlatamiz
from base.models import BaseModel
from blog.models import Status



class CoffeeModel(BaseModel):
     title = models.CharField(max_length=200)
     slug  = models.SlugField(unique=True, blank=True)
     description =  RichTextUploadingField()
     image = models.ImageField(upload_to='coffee_images/', null=True, blank=True)
     status = models.ForeignKey(Status, on_delete=models.SET_NULL, related_name='coffee_status', null=True, blank=True)
     sub_desc = models.CharField(max_length=200, verbose_name='qisqa komment')
     price = models.IntegerField()
     percentage = models.IntegerField()
     views = models.PositiveIntegerField(default=0)


     def __str__(self):
          return f'{self.title} - {self.image}'
     

     @property
     def get_new_price(self):
          if not self.percentage:
               return self.price
          return round(self.price * (100 - self.percentage)/100)
     

     def save(self, *args, **kwargs):
          if not self.slug:
               self.slug = slugify(self.title,  allow_unicode=True,)
          return super().save(*args, **kwargs)



class Testimonals(BaseModel):
     full_name = models.CharField(max_length=50)
     phone_number = models.CharField(max_length=13)
     image = models.ImageField(upload_to='testimonals_images/')
     message = models.TextField()


     def __str__(self):
          return f'{self.full_name} - {self.phone_number}'



class OrderModel(BaseModel):
     name = models.CharField(max_length=50)
     coffee = models.ForeignKey(CoffeeModel, on_delete=models.CASCADE, related_name='user_coffeess')
     humans = models.CharField(max_length=5, choices=[
          (1,1),
          (2,2),
          (3,3),
          (4,4),
          (5,5),
     ], default=1)
     text = models.CharField(max_length=200)


     def __str__(self):
          return f'{self.name} - {self.humans}'

base/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from .models import Blog, Status




class BlogView(View):
     def get(self, request):
          blognews = Blog.objects.filter(is_active=True)
          factik_blog = Blog.objects.filter(is_active=True, is_fact=True)


          context = {
               'blognews': blognews,
               'factik_blog': factik_blog,
          }
          return render(request, 'index.html', context)



class BlogDetailView(View):
     def get(self, request, slug):
          blogdetail = Blog.objects.get(slug=slug)
          blogdetail.views += 1
          blogdetail.save()
          

          context = {
               'blogdetail': blogdetail,
          }
          return render(request, 'blog_detail.html', context)



class BlogFactDetailView(View):
     def get(self, request, slug):
          fact_detail = get_object_or_404(Blog, slug=slug)
          fact_detail.views += 1
          fact_detail.save()

          context = {
               'fact_detail': fact_detail,
          }
          return render(request, 'blog_fact_coffee.html', context)    

coffee/views.py
from django.shortcuts import render
from django.views import View
from .models import CoffeeModel, Testimonals, OrderModel
from blog.models import Blog



def HomeView(request):
     coffees = CoffeeModel.objects.all()
     testimonals = Testimonals.objects.filter(is_active=True)
     orders = OrderModel.objects.all()
     
     context = {
          'coffees': coffees,
          'testimonals': testimonals,
          'orders': orders
     }
     return render(request, 'index.html', context)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
     <head>
          <!-- basic -->
          <meta charset="utf-8">
          <meta http-equiv="X-UA-Compatible" content="IE=edge">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <!-- mobile metas -->
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <meta name="viewport" content="initial-scale=1, maximum-scale=1">
          <!-- site metas -->
          <title>
               {% block title %}
               {% endblock title %}
          </title>
          <meta name="keywords" content="">
          <meta name="description" content="">
          <meta name="author" content="">
          <!-- bootstrap css -->
          <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
          <!-- style css -->
          <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
          <!-- Responsive-->
          <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
          <!-- fevicon -->
          <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
          <!-- Scrollbar Custom CSS -->
          <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
          <!-- font css -->
          <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;800&display=swap" rel="stylesheet">
          <!-- Tweaks for older IEs-->
          <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
     </head>
     <body>
          <div class="header_section">
               <div class="container">
                    <nav class="navbar navbar-expand-lg navbar-light bg-light">
                         <a class="navbar-brand"href="/"><img src="{% static 'images/logo.png' %}"></a>
                         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                         <span class="navbar-toggler-icon"></span>
                         </button>
                         <div class="collapse navbar-collapse" id="navbarSupportedContent">
                         <ul class="navbar-nav ml-auto">
                              <li class="nav-item active">
                              <a class="nav-link" href="/">Home</a>
                              </li>
                              <li class="nav-item">
                              <a class="nav-link" href="/">About</a>
                              </li>
                              <li class="nav-item">
                              <a class="nav-link" href="/">Coffees</a>
                              </li>
                              <li class="nav-item">
                              <a class="nav-link" href="/">Shop</a>
                              </li>
                              <li class="nav-item">
                              <a class="nav-link" href="/">Blog</a>
                              </li>
                              <li class="nav-item">
                              <a class="nav-link" href="/">Contact</a>
                              </li>
                         </ul>
                         <form class="form-inline my-2 my-lg-0">
                              <div class="login_bt">
                              <ul>
                                   <li><a href="#"><span class="user_icon"><i class="fa fa-user" aria-hidden="true"></i></span>Login</a></li>
                                   <li><a href="#"><i class="fa fa-search" aria-hidden="true"></i></a></li>
                              </ul>
                              </div>
                         </form>
                         </div>
                    </nav>
               </div>
               <!-- banner section start --> 
               <div class="banner_section layout_padding">
                    <div class="container">
                    <div id="banner_slider" class="carousel slide" data-ride="carousel">
                         <div class="carousel-inner">
                              {% for blog in blogcontext %}
                              {% if forloop.counter == 1 %}
                              <div class="carousel-item active">
                                   <div class="row">
                                        <div class="col-md-12">
                                        <div class="banner_taital_main">
                                             <h1 style="color: white; font-weight: bold; font-size: 50px;">{{ blog.title | slice:"15" }}</h1>
                                             <p class="banner_text">{{ blog.subtitle |slice:"70" }}</p>
                                             <div class="btn_main">
                                                  <!-- <div class="about_bt active"><a href="#">About Us</a></div> -->
                                                  <div class="callnow_bt"><a href="{% url 'blog:blogdetailurl' blog.slug %}">Деталь</a></div>
                                             </div>
                                        </div>
                                        </div>
                                   </div>
                              </div>
                              {% endif %}
                              {% endfor %}
                         </div>
                         
                    </div>
                    </div>
               </div>
               <!-- banner section end -->
          </div>
          <!-- header section end -->



          {% block content %}
          {% endblock content %}
          



          <!-- footer section start -->
          <div class="footer_section layout_padding">
          <div class="container">
               <div class="row">
                    <div class="col-md-12">
                    <div class="footer_social_icon">
                         <ul>
                         <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                         <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                         <li><a href="#"><i class="fa fa-youtube" aria-hidden="true"></i></a></li>
                         <li><a href="#"><i class="fa fa-github" aria-hidden="true"></i></a></li>
                         </ul>
                    </div>
                    <div class="location_text">
                         <ul>
                         <li>
                              <a href="#">
                              <i class="fa fa-phone" aria-hidden="true"></i><span class="padding_left_10">+01 1234567890</span>
                              </a>
                         </li>
                         <li>
                              <a href="#">
                              <i class="fa fa-envelope" aria-hidden="true"></i><span class="padding_left_10">demo@gmail.com</span>
                              </a>
                         </li>
                         </ul>
                    </div>
                    
                    </div>
               </div>
          </div>
          </div>
          <!-- footer section end -->
          <!-- copyright section start -->
          <div class="copyright_section">
          <div class="container">
               <div class="row">
                    <div class="col-sm-12">
                    <p class="copyright_text">2020 All Rights Reserved. Design by <a href="https://html.design">Free Html Templates</a>
                         Distribution by <a href="https://themewagon.com">ThemeWagon</a></p>
                    </div>
               </div>
          </div>
          </div>
          <!-- copyright section end -->
          <!-- Javascript files-->
          <script src="{% static 'js/jquery.min.js' %}"></script>
          <script src="{% static 'js/popper.min.js' %}"></script>
          <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
          <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
          <script src="{% static 'js/plugin.js' %}"></script>
          <!-- sidebar -->
          <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
          <script src="{% static 'js/custom.js' %}"></script>
     </body>
</html>

templates/blog_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
detail page
{% endblock title %}
{% block content %}


      <!-- about section start -->
      <div class="about_section layout_padding">
         <div class="container">
            <div class="about_section_2">
               <div class="row">
                  <div class="col-md-6"> 
                     <div class="about_taital_box">
                        <h1 class="about_taital">{{ blogdetail.title }}</h1>
                        <!-- <h1>{{ blogdetail.subtitle }}</h1> -->
                        <p class=" about_text" style="padding: 0 0 30px 0;">{{ blogdetail.content }}</p>
                        <br>
                        <br>
                     </div>
                  </div>
                  <div class="col-md-6"> 
                     <div class="image_iman"><img src="{{ blogdetail.image.url }}" class="about_img"></div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- about section end -->


{% endblock content %}

templates/blog_fact_coffee.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{{ fact_detail.title }} page
{% endblock title %}
{% block content %}


      <!-- about section start -->
      <div class="about_section layout_padding">
         <div class="container">
            <div class="about_section_2">
               <div class="row">
                  <div class="col-md-6"> 
                     <div class="about_taital_box">
                        <h1 class="about_taital">{{ fact_detail.title }}</h1>
                        <!-- <h1>{{ fact_detail.subtitle }}</h1> -->
                        <p class=" about_text" style="padding: 30px 0 0 0;">{{ fact_detail.content }}</p>
                        <br>
                        <br>
                     </div>
                  </div>
                  <div class="col-md-6"> 
                     <div class="image_iman"><img src="{{ fact_detail.image.url }} " class="about_img" style="padding: 0 0 100px 0;"></div>
                     <b><h6 style="color: black; font-size: 20px; font-family: cursive;"><i class="fa fa-eye" aria-hidden="true"></i> Просмотров: {{ fact_detail.views }}</h6></b>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- about section end -->


{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}
index page
{% endblock title %}
{% block content %}


      <!-- about section start -->
      <div class="about_section layout_padding">
         <div class="container">
            <div class="about_section_2">
               <div class="row">
                  <div class="col-md-6"> 
                     <div class="about_taital_box">
                        <h1 class="about_taital"></h1>
                        <h1 class="about_taital_1">{{ solo_coffee.title }}</h1>
                        <p class=" about_text">{{ solo_coffee.description }}</p>
                        <div class="readmore_btn"><a href="#">Читать далее</a></div>
                     </div>
                  </div>
                  <div class="col-md-6"> 
                     <div class="image_iman"><img src="{{ solo_coffee.image.url }}" class="about_img"></div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- about section end -->
      <!-- coffee section start -->
      <div class="coffee_section layout_padding">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <h1 class="coffee_taital">OUR Coffee OFFER</h1>
               </div>
            </div>
         </div>
         <div class="coffee_section_2">
            <div id="main_slider" class="carousel slide" data-ride="carousel">
               <div class="carousel-inner">
                  <div class="carousel-item active">
                     <div class="container-fluid">
                        <div class="row">
                           {% for coffee in coffees %}
                           {% if forloop.counter != 4 %}
                           <div class="col-lg-3 col-md-6">
                              <div class="coffee_img"><img style="width: 100%; height: 200px; object-fit: cover;" src="{{ coffee.image.url }}"></div>
                              <div class="coffee_box">
                                 <h3 class="types_text">{{ coffee.title }}</h3>
                                 <p class="looking_text">soon</p>
                                 <div class="read_bt"><a href="#">Read More</a></div>
                              </div>
                           </div>
                           {% endif %}
                           {% endfor %}
                        </div>
                     </div>
                  </div>
                  <div class="carousel-item">
                     <div class="container-fluid">
                        <div class="row">
                           {% for coffee in coffees %}
                           {% if forloop.counter == 4 %} 
                           <div class="col-lg-3 col-md-6">
                              <div class="coffee_img"><img style="width: 100%; height: 200px; object-fit: cover;" src="{{ coffee.image.url }}"></div>
                              <div class="coffee_box">
                                 <h3 class="types_text">{{ coffee.title }}</h3>
                                 <p class="looking_text">soon</p>
                                 <div class="read_bt"><a href="#">Read More</a></div>
                              </div>
                           </div>
                           {% endif %}
                           {% endfor %}
                        </div>
                     </div>
                  </div>
               </div>
               <a class="carousel-control-prev" href="#main_slider" role="button" data-slide="prev">
               <i class="fa fa-arrow-left"></i>
               </a>
               <a class="carousel-control-next" href="#main_slider" role="button" data-slide="next">
               <i class="fa fa-arrow-right"></i>
               </a>
            </div>
         </div>
      </div>
      <!-- coffee section end -->
      <!-- client section start -->
      <div class="client_section layout_padding">
         <div class="container">
            <div id="custom_slider" class="carousel slide" data-ride="carousel">
               <div class="carousel-inner">
                  <div class="carousel-item active">
                     <div class="row">
                        <div class="col-md-12">
                           <h1 class="about_taital">отзывы клиентов</h1>
                        </div>
                     </div>
                     <div class="client_section_2">
                        {% for test in testimonals %}
                        {% if forloop.counter == 1 %}
                        <div class="client_taital_main">
                           <div class="client_left">
                              <div class="client_img"><img src="{{ test.image.url }}"></div>
                           </div>
                           <div class="client_right">
                              <h3 class="moark_text">{{ test.full_name }}</h3>
                              <p class="client_text">{{ test.message }}</p>
                           </div>
                        </div>
                        {% endif %}
                        {% endfor %}
                     </div>
                  </div>
                  <div class="carousel-item">
                     <div class="row">
                        <div class="col-md-12">
                           <h1 class="about_taital">отзывы клиентов</h1>
                        </div>
                     </div>
                     <div class="client_section_2">
                        {% for test in testimonals %}
                        {% if forloop.counter != 1 %}
                        <div class="client_taital_main">
                           <div class="client_left">
                              <div class="client_img"><img src="{{ test.image.url }}"></div>
                           </div>
                           <div class="client_right">
                              <h3 class="moark_text">{{ test.full_name }}</h3>
                              <p class="client_text">{{ test.message }}</p>
                           </div>
                        </div>
                        {% endif %}
                        {% endfor %}
                     </div>
                  </div>
                  
               </div>
               <a class="carousel-control-prev" href="#custom_slider" role="button" data-slide="prev">
               <i class="fa fa-arrow-left"></i>
               </a>
               <a class="carousel-control-next" href="#custom_slider" role="button" data-slide="next">
               <i class="fa fa-arrow-right"></i>
               </a>
            </div>
         </div>
      </div>
      <!-- client section end -->
      <!-- blog section start -->
      <div class="blog_section layout_padding">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <h1 class="about_taital">фактические новости</h1>
               </div>
            </div>
            <div class="blog_section_2">
               <div class="row">
                  {% for blog in factik_blog %}
                  <div class="col-md-6">
                     <div class="blog_box">
                        <div class="blog_img"><img src="{{ blog.image.url }}" style="width: 600px; height: 300px;"></div>
                        <h4 class="date_text">{{ blog.status.name }}</h4>
                        <h4 class="prep_text">{{ blog.title }}</h4>
                        <p class="lorem_text">{{ blog.subtitle }}</p>
                     </div>
                     <div class="read_btn"><a href="{% url 'blog:blogfactdetailurl' blog.slug %}">Читать далее</a></div>
                  </div>
                  {% endfor %}
               </div>
            </div>
         </div>
      </div>
      <!-- blog section end -->
      <!-- contact section start -->
      <div class="contact_section layout_padding">
         <div class="container">
            <div class="row">
               <div class="col-sm-12">
                  <h1 class="contact_taital">Get In Touch</h1>
               </div>
            </div>
         </div>
         <div class="container-fluid">
            <div class="contact_section_2">
               <div class="row">
                  <div class="col-md-12">
                     <div class="mail_section_1">
                        <input type="text" class="mail_text" placeholder="Your Name" name="Your Name">
                        <input type="text" class="mail_text" placeholder="Your Email" name="Your Email">
                        <input type="text" class="mail_text" placeholder="Your Phone" name="Your Phone">
                        <textarea class="massage-bt" placeholder="Massage" rows="5" id="comment" name="Massage"></textarea>
                        <div class="send_bt"><a href="#">Send</a></div>
                     </div>
                  </div>
                  <div class="map_main">
                     <div class="map-responsive">
                        <iframe src="https://www.google.com/maps/embed/v1/place?key=AIzaSyA0s1a7phLN0iaD6-UE7m4qP-z21pH0eSc&amp;q=Eiffel+Tower+Paris+France" width="250" height="500" frameborder="0" style="border:0; width: 100%;" allowfullscreen=""></iframe>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- contact section end -->


{% endblock content %}